// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: handshake.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandshakeService_OneWayHandshake_FullMethodName = "/proto.HandshakeService/OneWayHandshake"
)

// HandshakeServiceClient is the client API for HandshakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandshakeServiceClient interface {
	OneWayHandshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
}

type handshakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandshakeServiceClient(cc grpc.ClientConnInterface) HandshakeServiceClient {
	return &handshakeServiceClient{cc}
}

func (c *handshakeServiceClient) OneWayHandshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, HandshakeService_OneWayHandshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HandshakeServiceServer is the server API for HandshakeService service.
// All implementations must embed UnimplementedHandshakeServiceServer
// for forward compatibility.
type HandshakeServiceServer interface {
	OneWayHandshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	mustEmbedUnimplementedHandshakeServiceServer()
}

// UnimplementedHandshakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandshakeServiceServer struct{}

func (UnimplementedHandshakeServiceServer) OneWayHandshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OneWayHandshake not implemented")
}
func (UnimplementedHandshakeServiceServer) mustEmbedUnimplementedHandshakeServiceServer() {}
func (UnimplementedHandshakeServiceServer) testEmbeddedByValue()                          {}

// UnsafeHandshakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandshakeServiceServer will
// result in compilation errors.
type UnsafeHandshakeServiceServer interface {
	mustEmbedUnimplementedHandshakeServiceServer()
}

func RegisterHandshakeServiceServer(s grpc.ServiceRegistrar, srv HandshakeServiceServer) {
	// If the following call pancis, it indicates UnimplementedHandshakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandshakeService_ServiceDesc, srv)
}

func _HandshakeService_OneWayHandshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandshakeServiceServer).OneWayHandshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandshakeService_OneWayHandshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandshakeServiceServer).OneWayHandshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HandshakeService_ServiceDesc is the grpc.ServiceDesc for HandshakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandshakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HandshakeService",
	HandlerType: (*HandshakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OneWayHandshake",
			Handler:    _HandshakeService_OneWayHandshake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "handshake.proto",
}
